# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def install_pods
  # Pods for Sample3

  pod 'CryptoSwift'
end

target 'Sample3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample3
  install_pods

end
